import Head from "next/head";
import Input from "components/inputs/input";
import Image from "next/image";
import styles from "styles/auth.module.css";
import Template from "components/auth/template";
export default function Home() {
  return (
    <div>
      <Head>
        <title>FaceCup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Template title="ثبت نام" type="register">
        <Input
          label="نام تیم (لاتین)"
          onChange={(e) => console.log(e.target.value)}
          pattern="[A-Za-z]{3}"
          icon={
            <Image
              height={24}
              width={24}
              src="/assets/icons/usercard.svg"
              alt="icon"
            />
          }
          info=" نام لاتین به‌عنوان نام کاربری شما جهت ورود به سیستم درنظر گرفته خواهد شد"
        />
        <Input
          label="نام تیم (فارسی)"
          icon={
            <Image
              height={24}
              width={24}
              src="/assets/icons/usercard.svg"
              alt="icon"
            />
          }
        />
        <Input
          label="شماره موبایل"
          type="number"
          icon={
            <Image
              height={24}
              width={24}
              src="/assets/icons/phone.svg"
              alt="icon"
            />
          }
          info="کدفعالسازی و احراز هویت به این شماره ارسال خواهد شد"
        />
      </Template>
    </div>
  );
}
