import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Dashboard from "../components/dashboard";
export default function Home() {
  return (
    <div>
      <Head>
        <title>FaceCup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="col">
        <div>
          <Link href="/auth/register">
            <a>auth</a>
          </Link>
        </div>
        <div>
          <Link href="/dashboard">
            <a>dashboard</a>
          </Link>
        </div>
      </div>
    </div>
  );
}
export async function getStaticProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
