import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "styles/landing.module.css";
import Navbar from "components/landing/navbar";
import Carousel from "components/landing/carousel";
import Sponsors from "components/landing/sponsors";
import About from "components/landing/about";
import Items from "components/landing/items";
import Items2 from "components/landing/items2";
import Stats from "components/landing/stats";
import Faq from "components/landing/faq";
import Footer from "components/landing/footer";
import Support from "components/landing/support";
import { FullPage, Slide } from "react-full-page";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FaceCup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <FullPage>
        <Slide>
          <Navbar />
          <Carousel />
        </Slide>
        <Slide>
          <About />
        </Slide>
        <Slide>
          <Items />
        </Slide>
        <Slide>
          <Items2 />
        </Slide>
        <Slide>
          <Sponsors />
        </Slide>
        <Slide>
          <Stats />
        </Slide>
        <Slide>
          <Faq />
        </Slide>
        <Slide>
          <Footer />
        </Slide>
      </FullPage>
      <Support />
    </div>
  );
}
export async function getStaticProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
